### ISSUE TITLE
How to customize favicon?

### ISSUE THREAD

**Issue by btofnc** [tomy-shen/TW-Style#1]
Hi There,

I changed the web favicon but it did not show correct icon every time. Some times will show the original "R" mark. What should I do to make it always show  my favicon?

**Comment by tomy-shen** [comment]
Hi, you can refer to this website：
https://www.w3.org/2005/10/howto-favicon

This usually happens because there is a problem with the format of the favicon and it cannot be displayed. 
Sometimes it will show the original "R" mark because of browser cache.
After successful implementation, remember to clear the browser cache first.
